// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/document-processor.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "documentprocessor";

export interface GenerateDocumentRequest {
  file: Uint8Array;
  filename: string;
  data: PlaceholderData[];
}

export interface PlaceholderData {
  id: string;
  key: string;
  type: string;
  value: string;
  width: number;
  height: number;
}

export interface MapValue {
  layerDataUrls: string[];
}

export interface GenerateDocumentResponse {
  file: Uint8Array;
}

export interface AnalyzeTemplateRequest {
  file: Uint8Array;
}

export interface PlaceholderMetadata {
  key: string;
  type: string;
  width: number;
  height: number;
}

export interface AnalyzeTemplateResponse {
  placeholders: PlaceholderMetadata[];
}

export const DOCUMENTPROCESSOR_PACKAGE_NAME = "documentprocessor";

export interface DocumentProcessorServiceClient {
  generate(request: GenerateDocumentRequest): Observable<GenerateDocumentResponse>;

  analyze(request: AnalyzeTemplateRequest): Observable<AnalyzeTemplateResponse>;
}

export interface DocumentProcessorServiceController {
  generate(
    request: GenerateDocumentRequest,
  ): Promise<GenerateDocumentResponse> | Observable<GenerateDocumentResponse> | GenerateDocumentResponse;

  analyze(
    request: AnalyzeTemplateRequest,
  ): Promise<AnalyzeTemplateResponse> | Observable<AnalyzeTemplateResponse> | AnalyzeTemplateResponse;
}

export function DocumentProcessorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generate", "analyze"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DocumentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DocumentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DOCUMENT_PROCESSOR_SERVICE_NAME = "DocumentProcessorService";
