// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/document-processor.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "documentprocessor";

export interface GenerateRequest {
  params: GenerateDocumentParams[];
}

export interface GenerateDocumentParams {
  file: Uint8Array;
  data: PlaceholderData[];
}

export interface PlaceholderData {
  id: string;
  key: string;
  type: string;
  value: string;
  width: number;
  height: number;
}

export interface MapValue {
  layerDataUrls: string[];
}

export interface GenerateResponse {
  documents: GeneratedDocument[];
}

export interface GeneratedDocument {
  file: Uint8Array;
}

export interface AnalyzeRequest {
  params: AnalyzeTemplateParams[];
}

export interface AnalyzeTemplateParams {
  file: Uint8Array;
}

export interface AnalyzeResponse {
  templates: AnalyzedTemplate[];
}

export interface AnalyzedTemplate {
  placeholders: PlaceholderMetadata[];
}

export interface PlaceholderMetadata {
  key: string;
  type: string;
  width: number;
  height: number;
}

export const DOCUMENTPROCESSOR_PACKAGE_NAME = "documentprocessor";

export interface DocumentProcessorServiceClient {
  generate(request: Observable<GenerateRequest>): Observable<GenerateResponse>;

  analyze(request: Observable<AnalyzeRequest>): Observable<AnalyzeResponse>;
}

export interface DocumentProcessorServiceController {
  generate(request: Observable<GenerateRequest>): Observable<GenerateResponse>;

  analyze(request: Observable<AnalyzeRequest>): Observable<AnalyzeResponse>;
}

export function DocumentProcessorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DocumentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["generate", "analyze"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DocumentProcessorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DOCUMENT_PROCESSOR_SERVICE_NAME = "DocumentProcessorService";
