// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/document-map-creator.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "documentmapcreator";

export interface CreateMapsRequest {
  maps: MapParams[];
}

export interface MapParams {
  id: string;
  width: number;
  height: number;
  center: number[];
  zoom: number;
  geojson: GeoJsonFeature[];
}

export interface GeoJsonFeature {
  type: string;
  geometry: Uint8Array;
  properties: Uint8Array;
}

export interface CreateMapsResponse {
  maps: MapResult[];
}

export interface MapResult {
  id: string;
  layerDataUrls: string[];
}

export const DOCUMENTMAPCREATOR_PACKAGE_NAME = "documentmapcreator";

export interface DocumentMapCreatorServiceClient {
  create(request: CreateMapsRequest): Observable<CreateMapsResponse>;
}

export interface DocumentMapCreatorServiceController {
  create(request: CreateMapsRequest): Promise<CreateMapsResponse> | Observable<CreateMapsResponse> | CreateMapsResponse;
}

export function DocumentMapCreatorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DocumentMapCreatorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DocumentMapCreatorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DOCUMENT_MAP_CREATOR_SERVICE_NAME = "DocumentMapCreatorService";
